export const loanRequests = [
  {
    id: 1,
    staffName: "Alice Smith",
    staffID: "A12345",
    loanAmount: 50000,
    purpose: "Home renovation",
  },
  {
    id: 2,
    staffName: "Bob Johnson",
    staffID: "B67890",
    loanAmount: 30000,
    purpose: "Education",
  },
  {
    id: 3,
    staffName: "Cathy Brown",
    staffID: "C54321",
    loanAmount: 75000,
    purpose: "Debt consolidation",
  },
  {
    id: 4,
    staffName: "David Miller",
    staffID: "D23456",
    loanAmount: 25000,
    purpose: "Vacation",
  },
  {
    id: 5,
    staffName: "Emily Wilson",
    staffID: "E98765",
    loanAmount: 10000,
    purpose: "Car repair",
  },
  {
    id: 6,
    staffName: "Frank Turner",
    staffID: "F34567",
    loanAmount: 18000,
    purpose: "Travel expenses",
  },
  {
    id: 7,
    staffName: "Grace Harris",
    staffID: "G45678",
    loanAmount: 28000,
    purpose: "Home appliances",
  },
  {
    id: 8,
    staffName: "Henry Martinez",
    staffID: "H56789",
    loanAmount: 42000,
    purpose: "Medical bills",
  },
  {
    id: 9,
    staffName: "Isabella Jackson",
    staffID: "I67890",
    loanAmount: 55000,
    purpose: "Wedding expenses",
  },
  {
    id: 10,
    staffName: "Jack White",
    staffID: "J78901",
    loanAmount: 32000,
    purpose: "Investment",
  },
  {
    id: 11,
    staffName: "Frank Blank",
    staffID: "F48922",
    loanAmount: 32000,
    purpose: "Investment",
  },
  {
    id: 12,
    staffName: "Liam Johnson",
    staffID: "L12345",
    loanAmount: 35000,
    purpose: "Home improvement",
  },
  {
    id: 13,
    staffName: "Mia Anderson",
    staffID: "M67890",
    loanAmount: 27000,
    purpose: "Vacation",
  },
  {
    id: 14,
    staffName: "Noah Thompson",
    staffID: "N54321",
    loanAmount: 42000,
    purpose: "Medical expenses",
  },
  {
    id: 15,
    staffName: "Olivia Smith",
    staffID: "O23456",
    loanAmount: 20000,
    purpose: "Education",
  },
  {
    id: 16,
    staffName: "Sophia Wilson",
    staffID: "S98765",
    loanAmount: 15000,
    purpose: "Car purchase",
  },
  {
    id: 17,
    staffName: "Aiden Brown",
    staffID: "A12345",
    loanAmount: 29000,
    purpose: "Debt consolidation",
  },
  {
    id: 18,
    staffName: "Emma Miller",
    staffID: "E67890",
    loanAmount: 80000,
    purpose: "Business startup",
  },
  {
    id: 19,
    staffName: "Jackson Davis",
    staffID: "J54321",
    loanAmount: 40000,
    purpose: "Home renovation",
  },
  {
    id: 20,
    staffName: "Ava Taylor",
    staffID: "A23456",
    loanAmount: 28000,
    purpose: "Travel expenses",
  },
  {
    id: 21,
    staffName: "Lucas Johnson",
    staffID: "L98765",
    loanAmount: 60000,
    purpose: "Wedding",
  },
  {
    id: 22,
    staffName: "Isabella Martinez",
    staffID: "I12345",
    loanAmount: 18000,
    purpose: "Home appliances",
  },
  {
    id: 23,
    staffName: "Liam Thompson",
    staffID: "L67890",
    loanAmount: 25000,
    purpose: "Investment",
  },
  {
    id: 24,
    staffName: "William Taylor",
    staffID: "W12398",
    loanAmount: 67000,
    purpose: "Home purchase",
  },
  {
    id: 25,
    staffName: "Yasmine Lee",
    staffID: "Y87912",
    loanAmount: 45000,
    purpose: "Business expansion",
  },
];

console.log(loanRequests);
